openapi: 3.0.0
info:
  title: backend REST API
  version: 0.0.1

servers:
  - url: https://backend:50000

paths:
  /image/{id}:
    get:
      summary: Get an image
      description: Retrieves an image from the backend.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      operationId: get_image
      responses:
        "200":
          description: OK
          content:
            image/*:
              schema:
                type: string
                format: binary
                description: Contents of the image as binary data
        "404":
          description: File not found
          content:
            text/plain:
              schema:
                type: string
                description: Error message
  
  /upload_image:
    post:
      summary: Upload an image
      description: Store an image to the backend. File is verified with a checksum.
      operationId: upload_image
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                sha1checksum:
                  type: string
                  required:
                    - sha1checksum
                file:
                  type: string
                  format: binary
                  required:
                    - file
                  
      
      responses:
        "200":
          description: URL of uploaded file
          content:
            text/plain:
              schema:
                type: string

  /list_images:
    get:
      summary: Get a list of images
      description: Retrieves a list of available image URLs
      operationId: list_images
      responses:
        "200":
          description: List retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
