# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% ../00_core.ipynb 2
import fastcore.test as ft

# %% ../00_core.ipynb 3
#| test case CoreTester unittest.TestCase

# %% ../00_core.ipynb 6
def test_say_hello():
    def say_hello(to):
        "Say hello to somebody"
        return f'Hello {to}!'
    
    ft.test_eq(say_hello('Isaac'), 'Hello Isaac!')
