openapi: 3.0.0
info:
  title: backend REST API
  version: 0.0.1
servers:
- url: https://backend:50000
paths:
  /image/{id}:
    get:
      description: Retrieves an image from the backend.
      operationId: get_image
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            image/*:
              schema:
                description: Contents of the image as binary data
                format: binary
                type: string
          description: OK
        "404":
          content:
            text/plain:
              schema:
                description: Error message
                type: string
          description: File not found
      summary: Get an image
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /list_images:
    get:
      description: Retrieves a list of available image URLs
      operationId: list_images
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: List retrieved
      summary: Get a list of images
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /upload_image:
    post:
      description: Store an image to the backend. File is verified with a checksum.
      operationId: upload_image
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/upload_image_request'
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: URL of uploaded file
      summary: Upload an image
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    upload_image_request:
      properties:
        sha1checksum:
          required:
          - sha1checksum
          type: string
        file:
          format: binary
          required:
          - file
          type: string
      type: object
