# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tflm_hello_world',
                'doc_host': 'https://Origami-TinyML.github.io',
                'git_url': 'https://github.com/Origami-TinyML/tflm_hello_world',
                'lib_path': 'tflm_hello_world'},
  'syms': {'tflm_hello_world.core': {'tflm_hello_world.core.foo': ('core.html#foo', 'tflm_hello_world/core.py')}}}
